a = float(input("Number1: "))
b = float(input("Number2: "))
print(f"Сумма = {a+b}\nРазность = {a-b}\nПроизведение = {a*b}")
print(f"Частное = {a/b}\nВозведение в степень = {a**b}")
print(f"Частное по модулю = {a%b}\nЦелое частное = {a//b}")
